let data = [
    {id:1, title:"perfume", price: 50, imageUrl: "images/product1.webp",},
    {id:2, title:"cream", price: 40, imageUrl: "images/product2.jpg"},
    {id:3, title:"skin care", price: 100, imageUrl: "images/product3.jpg"},
    {id:4, title:"skin care", price: 120, imageUrl: "images/product4.jpg"},
    {id:5, title:"skin care", price: 100, imageUrl: "images/product5.jpg"},
    {id:16, title:"skin care", price: 90, imageUrl: "images/product6.jpg"},
    {id:7, title:"glasses", price: 100, imageUrl: "images/glasses.jpg"},
    {id:8, title:"headphone", price: 80, imageUrl: "images/headphone1.avif",},
    {id:9, title:"phone", price: 500, imageUrl: "images/phone.jpg"},
    {id:10, title:"watch", price: 200, imageUrl: "images/watch.jpg"},
    {id:11, title:"laptop", price: 800, imageUrl: "images/laptop.jpg"},
    {id:12, title:"clothes", price: 200, imageUrl: "images/clothes.jpg",},
    {id:13, title:"headphone", price: 70, imageUrl: "images/headphone.jpg"},
    {id:14, title:"clothes", price: 150, imageUrl: "images/jacket.jpg"},
    {id:15, title:"hat", price: 30, imageUrl: "images/hat.jpg"},
    {id:16, title:"camera", price: 200, imageUrl: "images/camera.jpg"},
];
