let data = [
    {id:1, title:"perfume", price: 50, imageUrl: "images/product1.webp", amount: 1},
    {id:2, title:"cream", price: 40, imageUrl: "images/product2.jpg", amount: 1},
    {id:3, title:"jelly", price: 100, imageUrl: "images/product3.jpg", amount: 1},
    {id:4, title:"pink", price: 120, imageUrl: "images/product4.jpg", amount: 1},
    {id:5, title:"skin care", price: 100, imageUrl: "images/product5.jpg", amount: 1},
    {id:16, title:"mist", price: 90, imageUrl: "images/product6.jpg", amount: 1},
    {id:7, title:"glasses", price: 100, imageUrl: "images/glasses.jpg", amount: 1},
    {id:8, title:"headphone", price: 80, imageUrl: "images/headphone1.avif", amount: 1},
    {id:9, title:"phone", price: 500, imageUrl: "images/phone.jpg", amount: 1},
    {id:10, title:"watch", price: 200, imageUrl: "images/watch.jpg", amount: 1},
    {id:11, title:"laptop", price: 800, imageUrl: "images/laptop.jpg", amount: 1},
    {id:12, title:"clothes", price: 200, imageUrl: "images/clothes.jpg", amount: 1},
    {id:13, title:"headphone", price: 70, imageUrl: "images/headphone.jpg", amount: 1},
    {id:14, title:"jacket", price: 150, imageUrl: "images/jacket.jpg", amount: 1},
    {id:15, title:"hat", price: 30, imageUrl: "images/hat.jpg", amount: 1},
    {id:16, title:"camera", price: 200, imageUrl: "images/camera.jpg", amount: 1},
];
